version: '3.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    container_name: elasticsearch
    ports:
    - "9200:9200"
    - "9300:9300"
    networks:
    - elk
    environment:
      discovery.type: "single-node"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.2
    container_name: kibana
    ports:
    - "5601:5601"
    networks:
    - elk
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
networks:
  elk:
          #    driver: bridge
          #    internal: true
